### PR TITLE
LPS-136840 Add test to check that a site member can access an image in a folder through the URL

### PR DESCRIPTION
**Pull request by DebSouza**
https://issues.liferay.com/browse/LPS-136840

### CODE REVIEW

**Comment by DebSouza** [comment]
ci:test:sf

**Comment by DebSouza** [comment]
ci:test:sf

**Comment by DebSouza** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
See: https://github.com/austinchiang/liferay-portal/pull/1211

**Pull request closed without merging**
