### PR TITLE
LPS-156487 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-156487

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:help

**Comment by Jeremy-Ch** [comment]
ci:test:blogs

**Comment by Jeremy-Ch** [comment]
ci:test:blogs

**Comment by liuxingye** [comment]
ci:test:blogs

**Comment by Jeremy-Ch** [comment]
ci:test:blogs

**Comment by Jeremy-Ch** [comment]
ci:test:blogs

**Pull request closed without merging**
